version: "3.7"

x-env-vars: &env-vars
  - PGUSER=postgres
  - PGHOST=postgres
  - PGPASSWORD=postgres_password
  - PGDATABASE=postgres
  - PGPORT=5432

services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment: *env-vars
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./src:/app/src
      - ./db:/app/db
  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment: *env-vars
    volumes:
      - /app/node_modules
      - ./src:/app/src
      - ./db:/app/db
    command: ["npm", "run", "test"]
