version: "3.7"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  server:
    build: .
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPASSWORD=postgres_password
      - PGDATABASE=postgres
      - PGPORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - ./db:/app/db
